# Generated by Django 3.2.18 on 2023-04-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vaccination_centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('working_hours', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('slots_per_day', models.CharField(max_length=200)),
                ('ucontact', models.CharField(max_length=10)),
            ],
        ),
    ]
